# Generated by Django 5.0.2 on 2024-03-07 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_listing_delete_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='type',
            field=models.TextField(default='Other'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='finish_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 14, 18, 49, 17, 571767, tzinfo=datetime.timezone.utc)),
        ),
    ]
