# Generated by Django 5.0.2 on 2024-03-11 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_listing_finish_at_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.TextField(default='Selling'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='finish_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 19, 12, 31, 73981, tzinfo=datetime.timezone.utc)),
        ),
    ]
