# Generated by Django 5.0.2 on 2024-03-11 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_listing_finish_at_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='finish_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 19, 50, 35, 549448, tzinfo=datetime.timezone.utc)),
        ),
    ]
