# Generated by Django 5.0.2 on 2024-03-11 21:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_messages_listing_id_alter_listing_finish_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='listing_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.listing'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='finish_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 21, 11, 55, 373108, tzinfo=datetime.timezone.utc)),
        ),
    ]
