# Generated by Django 5.0.2 on 2024-03-13 03:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_messages_listing_id_alter_listing_finish_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='description',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mobile_number',
        ),
        migrations.AlterField(
            model_name='listing',
            name='finish_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 20, 3, 9, 10, 609153, tzinfo=datetime.timezone.utc)),
        ),
    ]
