# Generated by Django 5.0.2 on 2024-03-18 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_order_description_remove_order_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='finish_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 25, 17, 44, 27, 576299, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.TextField(default='Other', max_length=255),
        ),
    ]
